services:

  ph-eye-hospitals:
    image: philterd/ph-eye-hospitals:1.2.5
    container_name: philter-ph-eye-hospitals-1
    ports:
      - "5000"
    networks:
      - philter

  ph-eye-en:
    image: philterd/ph-eye:1.2.1
    container_name: philter-ph-eye-en-1
    ports:
      - "5000"
    networks:
      - philter

  ph-eye-en-medical-conditions:
    image: philterd/ph-eye-medical-conditions:1.2.3
    container_name: philter-ph-eye-en-medical-conditions-1
    ports:
      - "5000"
    networks:
      - philter

  ph-eye-fr-persons:
    image: philterd/ph-eye-fr-persons:1.2.4
    container_name: philter-ph-eye-fr-persons-1
    ports:
      - "5000"
    networks:
      - philter

  ph-eye-fr-medical:
    image: philterd/ph-eye-fr-medical:1.2.3
    container_name: philter-ph-eye-fr-medical-1
    ports:
      - "5000"
    networks:
      - philter

  philter:
    image: philterd/philter:3.4.0-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - ./philter.properties:/opt/philter/philter.properties
      - ./policies/:/opt/philter/policies/
    networks:
      - philter

networks:
  philter:
